config/routes.rb
Workspace::Application.routes.draw do

  resources :zones, only: [:index,:new,:create,:show]

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  get 'sign-up' => 'users#new', as: 'sign_up'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :zones
	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { minimum: 3 }
  validates :email,format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/models/zone.rb
class Zone < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/secure_application_controller.rb
class SecureApplicationController < ApplicationController
  include SessionsHelper

  before_action :require_login

  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path # halts request cycle
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      # login
      session[:user_id] = @user.id
      flash[:success] = 'Successfully signed in!'
      redirect_to user_path(id: @user.id)
    else
      # incorrect password or username combination
      flash.now[:danger] = 'Invalid username or password'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'Successfully logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def index
    if logged_in?
      @user = User.all
    else
      redirect_to login_path, danger: "You must be logged in to access this section"
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to user_path(id: @user.id), notice: "Thanks for Signing Up!"
    else
      flash.now[:danger] = @user.errors
      render :new
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = "Successfully Update your profile"
      redirect_to user_path(id: @user.id)
    else
      flash.now[:danger] = "Failed to update your profile"
      render 'edit'
    end
  end

  def destroy
  end

  private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

end

app/controllers/zones_controller.rb
class ZonesController < SecureApplicationController

  def index
    @country = Country.all
  end

  def new
  end

  def create
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Zone', root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <%- if session[:user_id].nil? %>
          <li><%= link_to 'Sign Up', sign_up_path %></li>
          <li><%= link_to 'Sign In', login_path %></li>
        <%- else %>
          <li><%= link_to "Settings", edit_user_path(session[:user_id]) %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete  %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="row">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end %>
  </div>
</div>

<%= yield %>


<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p>Copyright &copy; 2014</p>
    </div>
  </div>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal"}  do |f|%>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <h1>Update your profile</h1>

      <%= form_for(@user) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="form-group">

          <%= f.submit "Save changes", class: "btn btn-primary" %>
        </div>
      <% end %>


    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <ol class="breadcrumb">
        <li><a href= <%= root_path %>>Home</a></li>
        <li class="active">Profile</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <div class="page-header">
        <h1>Profile</h1>
      </div>

      <div class="col-md-12 col-xs-12">
        <%= @user.inspect %>
      </div>
    </div>
  </div>
</div>

<script>

</script>

app/views/users/new.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <ol class="breadcrumb">
        <li><a href= <%= root_path %>>Home</a></li>
        <li class="active">Sign Up</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <div class="page-header">
        <h1>Join Us now</h1>
      </div>

      <div class="col-md-6 col-xs-12">
        <%= render 'form' %>
      </div>

      <div class="col-md-6 col-xs-12">
        <div class="jumbotron">
          <h1>Why Join Us?</h1>
          <p>Because we are AWESOME!! =D </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <ol class="breadcrumb">
        <li><a href= <%= root_path %>>Home</a></li>
        <li class="active">Profile</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <div class="page-header">
        <h1>Profile</h1>
      </div>

      <table class="table">

        <thead>
          <tr>
            <th></th>
            <th>Details</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Name</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>Email</td>
            <td><%= @user.email %></td>
          </tr>

        </tbody>
      </table>


    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <ol class="breadcrumb">
        <li><a href= <%= root_path %>>Home</a></li>
        <li class="active">About</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <div class="page-header">
        <h1>About <small>something about this project</small></h1>
      </div>
    </div>
  </div>
</div>

app/views/welcome/contact.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <ol class="breadcrumb">
        <li><a href= <%= root_path %>>Home</a></li>
        <li class="active">Contact</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <div class="page-header">
        <h1>Contact <small>Anything want to share with us?</small></h1>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <ol class="breadcrumb">
        <li class="active">Home</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <div class="jumbotron">
		    <h1>Welcome</h1>
		    <p>Feel like understand more about time zone around your locations?</p>
    
		    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
		  </div>
    </div>
  </div>
</div>

app/views/zones/index.html.erb
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <ol class="breadcrumb">
        <li><a href= <%= root_path %>>Home</a></li>
        <li class="active">Zones</li>
      </ol>
    </div>
  </div>
</div>
<div class="row">
  <div class="container">
    <div class="col-md-12 col-xs-12">
      <div class="page-header">
        <h1>List of Country Zones <small>something about the country</small></h1>
      </div>
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Country Name</th>
              <th>Country Shortcode</th>
            </tr>
          </thead>
          <tbody>
            <% count = 1 %>
            <% @country.each do |key, value| %>
              <% if count%2 == 0 %>
                <tr class="info">
              <% else %>
                <tr class="">
              <% end %>
                <td><%= count %></td>
                <td><%= key %></td>
                <td><%= value %></td>
              </tr>
              <% count += 1 %>
            <% end %>



          </tbody>
        </table>

      <div>

      </div>
    </div>
  </div>
</div>